name: Bug form
description: File a Issue report
title: "[BUG]: "
labels: ["help wanted"]
# assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please fill out the issue report form
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: On which platform?
      options:
        - iOS
        - Android
    validations:
      required: true
  - type: input
    id: device_model
    attributes:
      label: Device Model
      description: On what model you are experiencing issues?
      placeholder: iPhone XR
    validations:
      required: true
  - type: input
    id: wallet
    attributes:
      label: Wallet Address
      description: Optional
      placeholder: 0x...
    validations:
      required: false
  - type: input
    id: nft_id
    attributes:
      label: NFT ID
      description: Optional
      placeholder: 12345
    validations:
      required: false
  - type: input
    id: app_version
    attributes:
      label: RunBlox App version
      description: Which version you are experiencing issues?
      placeholder: 1.2.2.131
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        1. At 2022.06.15 23:12 PM UTC
        2. Go to '...'
        3. Click on '....'
        4. Scroll down to '....'
        5. See error
        6. Attach a screenshot...
    validations:
      required: true
